import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/redux/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: 'Next - InitPro',
    template: "%s - Next - InitPro",
  },
  description: "Generated by InitPro with create next app",
  keywords: ['next js', 'initpro']
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ReduxProvider>
        <body className={inter.className}>{children}</body>
      </ReduxProvider>
    </html>
  );
}
