
export const metadata = {
  title: "Admin",
  description: "Generated by InitPro with create next app",
};

export default function RootLayout({ children }) {
  return (
    <main>
      {children}
    </main>
  );
}
